# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe97be2e33663bb39580131ad79c8a866413a513e1871c6d65ebfea40cee026fafbd2edb3d6883858f6c51e19a77a8e8aa2122945714dbe4d46e4dc442b9402

test:
  secret_key_base: dbeff475a7299ee35d0fb583053c29b04fae7fe2717ccdccc614df8b9d8cd8a3c231f43e53f7c753825edbe50c3885809524d7423a771fd46a6ccdad81ddbfee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
